# Generated by Django 6.0.4 on 2026-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_jobapplication_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата зміни статусу'),
        ),
    ]
