# Generated by Django 6.0.4 on 2026-04-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_jobapplication_status_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('date', models.DateField(verbose_name='Дата')),
                ('event_type', models.CharField(choices=[('interview', 'Співбесіда'), ('deadline', 'Дедлайн'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип події')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.jobapplication', verbose_name='Вакансія')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['date'],
            },
        ),
    ]
